### ISSUE TITLE
multi

### ISSUE THREAD

**Issue by dotsp** [Riketta/Warcraft-Fishman#7]
hi there,

thank you for your work on this - is there a way of modifying this to allow work on multiple instances of wow? i.e in multiple smaller sized windows?

right now, i understand that wow has to be in fullscreen as the scanner works anchored in the centre.

**Comment by Riketta** [comment]
I think it's impossible due to we have to use cursor all time. But you can try to use some virtual container for each WoW client, like VirtualBox.
